name: Test Semgrep + Docker Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semgrep-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install Semgrep
      - name: Install Semgrep
        run: pip install semgrep

      # Step 3: Run Semgrep scan (ignore Flask host warning)
      - name: Run Semgrep Scan
        run: semgrep --config=p/ci --exclude-rule python.flask.security.audit.app-run-param-config.avoid_app_run_with_bad_host

      # Step 4: Docker login
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5: Build & Push Docker Images
      - name: Build & Push Docker Images
        run: |
          SERVICES=("cart" "inventory" "users" "orders" "payments")
          for SERVICE in "${SERVICES[@]}"; do
            IMAGE_TAG="${{ secrets.DOCKER_USERNAME,, }}/${SERVICE,,}:${GITHUB_SHA::7}"
            echo "Building and pushing $SERVICE -> $IMAGE_TAG"
            docker build -t $IMAGE_TAG ./$SERVICE
            docker push $IMAGE_TAG
          done
