name: Test Semgrep + Docker Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  semgrep-docker:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      SERVICES=("service1" "service2" "service3" "service4" "service5")

    steps:
      # Step 1: Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Run Semgrep scan (ignore Flask host warning)
      - name: Run Semgrep Scan
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"
          args: "--exclude-rule python.flask.security.audit.app-run-param-config.avoid_app_run_with_bad_host"

      # Step 3: Docker login
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 4: Build & Push Docker Images
      - name: Build & Push Docker Images
        run: |
          for SERVICE in ${SERVICES[@]}; do
            IMAGE_TAG="${DOCKERHUB_USERNAME}/${SERVICE}:${GITHUB_SHA::7}"
            echo "Building and pushing $SERVICE -> $IMAGE_TAG"
            docker build -t $IMAGE_TAG ./$SERVICE
            docker push $IMAGE_TAG
          done
